services:
  elasticsearch:
    image: elasticsearch:7.17.15
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ['CMD-SHELL', 'curl -fsS "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

  geonetwork:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: geonetwork-gemini23:4.2
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - geonetwork:/catalogue-data
    environment:
      WEBAPP_CONTEXT_PATH: /geonetwork
      DATA_DIR: /catalogue-data
      ES_HOST: elasticsearch
      ES_PORT: 9200
      ES_PROTOCOL: http
      JAVA_OPTS: -Xms512m -Xmx1024m -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=ERROR
      GN_CONFIG_PROPERTIES: >-
        -Dgeonetwork.dir=/catalogue-data
        -Dgeonetwork.formatter.dir=/catalogue-data/data/formatter
        -Dgeonetwork.schema.dir=/opt/geonetwork/WEB-INF/data/config/schema_plugins
        -Dgeonetwork.indexConfig.dir=/opt/geonetwork/WEB-INF/data/config/index
        -Dgeonetwork.schemapublication.dir=/opt/geonetwork/WEB-INF/data/resources/schemapublication
        -Dgeonetwork.htmlcache.dir=/opt/geonetwork/WEB-INF/data/resources/htmlcache
        -Des.host=elasticsearch
        -Des.protocol=http
        -Des.port=9200
        -Des.url=http://elasticsearch:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/geonetwork/srv/api/site || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 30

volumes:
  esdata:
  geonetwork:
